version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - 80:80
      - 443:443
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 3306:3306
